# Project name (used as prefix for containers and images)
name: "microservices"

services:
  # MICROSERVICES
  api-gateway:
    build:
      context: ./microservices-api-gateway
      target: development
      args:
        - MODE=development
    container_name: api-gateway
    ports:
      - 4000:4000
    depends_on:
      user-service:
        condition: service_healthy
      authentication-service:
        condition: service_healthy
      upload-service:
        condition: service_healthy
      video-catalog-service:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./microservices-api-gateway:/app
    labels:
      log_target: "microservice"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 10s
      timeout: 3s
      retries: 10

  user-service:
    build:
      context: ./microservices-user-service
      target: development
    container_name: user-service
    ports:
      - 5000:5000 # gRPC
      - 5010:5010 # HTTP (prometheus)
    depends_on:
      user-db:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./microservices-user-service:/app
      - /app/node_modules
    labels:
      log_target: "microservice"
    healthcheck:
      test: ["CMD", "grpc-health-probe", "-addr=localhost:5000"]
      interval: 10s
      timeout: 3s
      retries: 10

  authentication-service:
    build:
      context: ./microservices-authentication-service
      target: development
      args:
        - MODE=development
    container_name: authentication-service
    ports:
      - 5001:5001 # gRPC
      - 5011:5011 # HTTP (prometheus)
    depends_on:
      user-service:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./microservices-authentication-service:/app
    labels:
      log_target: "microservice"
    healthcheck:
      test: ["CMD", "grpc-health-probe", "-addr=localhost:5001"]
      interval: 10s
      timeout: 3s
      retries: 10

  upload-service:
    build:
      context: ./microservices-upload-service
      target: development
      args:
        - MODE=development
    container_name: upload-service
    ports:
      - 5002:5002 # gRPC
      - 5012:5012 # HTTP (prometheus)
    depends_on:
      rabbitmq:
        condition: service_healthy
      encode-service:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./microservices-upload-service:/app
    labels:
      log_target: "microservice"
    healthcheck:
      test: ["CMD", "grpc-health-probe", "-addr=localhost:5002"]
      interval: 10s
      timeout: 3s
      retries: 10

  encode-service:
    build:
      context: ./microservices-encode-service
      target: development
      args:
        - MODE=development
    container_name: encode-service
    ports:
      - 5004:5004 # gRPC
      - 5014:5014 # HTTP (prometheus)
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./microservices-encode-service:/app
    labels:
      log_target: "microservice"
    healthcheck:
      test: ["CMD", "grpc-health-probe", "-addr=localhost:5004"]
      interval: 10s
      timeout: 3s
      retries: 10

  video-catalog-service:
    build:
      context: ./microservices-video-catalog-service
      target: development
      args:
        - MODE=development
    container_name: video-catalog-service
    ports:
      - 5003:5003 # gRPC
      - 5013:5013 # HTTP (prometheus)
    depends_on:
      rabbitmq:
        condition: service_healthy
      video-catalog-db:
        condition: service_healthy
      user-service:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./microservices-video-catalog-service:/app
    labels:
      log_target: "microservice"
    healthcheck:
      test: ["CMD", "grpc-health-probe", "-addr=localhost:5003"]
      interval: 10s
      timeout: 3s
      retries: 10

  # DATABASES
  user-db:
    image: postgres:14
    container_name: user-db
    # ports:
    #   - 5432:5432
    environment:
      - POSTGRES_DB=microservices_user_service
      - POSTGRES_PASSWORD=password
    volumes:
      - ./docker/user-db/data:/var/lib/postgresql/data
      - ./docker/user-db/config/postgresql.conf:/etc/postgresql/postgresql.conf
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U postgres -d microservices_user_service"]
      interval: 10s
      timeout: 5s
      retries: 10

  video-catalog-db:
    image: postgres:14
    container_name: video-catalog-db
    # ports:
    #   - 5433:5432
    environment:
      - POSTGRES_DB=microservices_video_catalog_service
      - POSTGRES_PASSWORD=password
    volumes:
      - ./docker/video-catalog-db/data:/var/lib/postgresql/data
      - ./docker/video-catalog-db/config/postgresql.conf:/etc/postgresql/postgresql.conf
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d microservices_video_catalog_service",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:8.13.0
    container_name: pgadmin
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - ./docker/pgadmin/data:/var/lib/pgadmin
    attach: false

  # CACHES
  redis:
    image: redis:7.2
    container_name: redis
    # ports:
    #   - 6379:6379
    volumes:
      - ./docker/redis/data:/data
      - ./docker/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 10

  # MESSAGE BROKERS
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      # - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=default
      - RABBITMQ_DEFAULT_PASS=default
    volumes:
      - ./docker/rabbitmq/config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./docker/rabbitmq/data:/var/lib/rabbitmq/mnesia
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 10

  # MONITORING, LOGGING, TRACING
  grafana:
    image: grafana/grafana-enterprise:11.3.0
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./docker/grafana/data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    attach: false
    depends_on:
      - loki
      - prometheus

  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./docker/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./docker/prometheus/data:/prometheus
    attach: false

  loki:
    image: grafana/loki:2.9.7
    container_name: loki
    # ports:
    #   - 3100:3100
    volumes:
      - ./docker/loki/data:/loki
      # - ./docker/loki/config/config.yaml:/etc/loki/config.yaml
    # command: -config.file=/etc/loki/config.yaml
    attach: false

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/alloy/config/config.alloy:/etc/alloy/config.alloy
      - ./docker/alloy/data:/var/lib/alloy/data
    ports:
      - 3001:12345
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    depends_on:
      - loki
    attach: false

  jaeger:
    image: jaegertracing/all-in-one:1.56
    container_name: jaegar
    ports:
      - "16686:16686" # UI
      # - "4318:4318" # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  rabbitmq-exporter:
    image: kbudde/rabbitmq-exporter:1.0.0
    container_name: rabbitmq-exporter
    # ports:
    #   - "9419:9419"
    environment:
      - RABBIT_URL=http://rabbitmq:15672
      - RABBIT_USER=default
      - RABBIT_PASSWORD=default
    depends_on:
      rabbitmq:
        condition: service_healthy
    attach: false

  redis-exporter:
    image: oliver006/redis_exporter:v1.67.0
    container_name: redis-exporter
    # ports:
    #   - 9121:9121
    environment:
      - REDIS_ADDR=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    attach: false

  user-db-exporter:
    image: prometheuscommunity/postgres-exporter:v0.16.0
    container_name: user-db-exporter
    # ports:
    #   - 9187:9187
    environment:
      - DATA_SOURCE_URI=user-db:5432/microservices_user_service?sslmode=disable
      - DATA_SOURCE_USER=postgres
      - DATA_SOURCE_PASS=password
    depends_on:
      user-db:
        condition: service_healthy
    attach: false

  video-catalog-db-exporter:
    image: prometheuscommunity/postgres-exporter:v0.16.0
    container_name: video-catalog-db-exporter
    # ports:
    #   - 9187:9187
    environment:
      - DATA_SOURCE_URI=video-catalog-db:5432/microservices_video_catalog_service?sslmode=disable
      - DATA_SOURCE_USER=postgres
      - DATA_SOURCE_PASS=password
    depends_on:
      video-catalog-db:
        condition: service_healthy
    attach: false
