apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq
  namespace: datastores
data:
  enabled_plugins: |
    [rabbitmq_management].
  rabbitmq.conf: |
    listeners.tcp.default = 5672
    management.tcp.port = 15672
    loopback_users.guest = false
