apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: datastores
spec:
  ports:
    - name: tcp
      port: 5672
    - name: management
      port: 15672
  clusterIP: None
  selector:
    app: rabbitmq
