apiVersion: v1
kind: Service
metadata:
  name: encode-service
  namespace: microservices
spec:
  type: ClusterIP
  selector:
    app: encode-service
  ports:
    - name: grpc
      protocol: TCP
      port: 5004
      targetPort: 5004
    - name: http
      protocol: TCP
      port: 5014
      targetPort: 5014
