{
 "title": "Microservices Logs",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "service_name", "label": "Service", "query": "label_values(service_name)" }
  ]
 },
 "panels": [
  {
   "title": "Logs in Bytes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "bytes_over_time({service_name=\"$service_name\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Log Lines",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({service_name=\"$service_name\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Error Logs Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate({service_name=\"$service_name\"} |= \"error\" [5m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{service_name=\"$service_name\"}"
    }
   ]
  }
 ]
}