{
 "title": "Microservices",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Overall Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Gateway",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 112 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(api_gateway_service_health_status{})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Video Catalog Service",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 112 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(video_catalog_service_service_health_status{})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Upload Service",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 112 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(upload_service_service_health_status{})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Authentication Service",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 112 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(authentication_service_service_health_status{})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "User Service",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 112 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(user_service_service_health_status{})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Encode Service",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 112 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(encode_service_service_health_status{})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Redis",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 149 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "redis_up", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "RabbitMQ",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 149 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "rabbitmq_up", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "User DB",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 149 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_up{instance=\"user-db-exporter:9187\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Video Catalog DB",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 149 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_up{instance=\"user-db-exporter:9187\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "API Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Latency",
     "type": "timeseries",
     "description": "Shows the 95th percentile latency for each gRPC method.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(api_gateway_request_duration_seconds_bucket[1m])) by (le, method))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests by Method",
     "type": "timeseries",
     "description": "Displays the request rate for each gRPC method.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
     "targets": [
      {
       "expr": "sum(rate(api_gateway_requests_total[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error Rate",
     "type": "piechart",
     "description": "Visualizes the proportion of failed requests.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "expr": "sum by(status) (rate(api_gateway_requests_total{status!=\"200\"}[24h]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Requests",
     "type": "timeseries",
     "description": "Displays the total requests grouped by method and status.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
     "targets": [
      {
       "expr": "sum(user_service_grpc_requests_total) by (method, status)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "User Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Latency",
     "type": "timeseries",
     "description": "Shows the 95th percentile latency for each gRPC method.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 220 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(user_service_grpc_request_duration_seconds_bucket[1m])) by (le, method))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests by Method",
     "type": "timeseries",
     "description": "Displays the request rate for each gRPC method.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 220 },
     "targets": [
      {
       "expr": "sum(rate(user_service_grpc_requests_total[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error Rate",
     "type": "piechart",
     "description": "Visualizes the proportion of failed requests.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 228 },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "expr": "sum by(status) (rate(user_service_grpc_requests_total{status!=\"OK\"}[24h]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Requests",
     "type": "timeseries",
     "description": "Displays the total requests grouped by method and status.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 228 },
     "targets": [
      {
       "expr": "sum(user_service_grpc_requests_total) by (method, status)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Authentication Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error Rate",
     "type": "piechart",
     "description": "Visualizes the proportion of failed requests.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 301 },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "expr": "sum by(status) (rate(authentication_service_grpc_requests_total{status!=\"OK\"}[24h]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests by Method",
     "type": "timeseries",
     "description": "Displays the request rate for each gRPC method.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 301 },
     "targets": [
      {
       "expr": "sum(rate(authentication_service_grpc_requests_total[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Latency",
     "type": "timeseries",
     "description": "Shows the 95th percentile latency for each gRPC method.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 333 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(authentication_service_grpc_request_duration_seconds_bucket[1m])) by (le, method))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Requests",
     "type": "timeseries",
     "description": "Displays the total requests grouped by method and status.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 333 },
     "targets": [
      {
       "expr": "sum(authentication_service_grpc_requests_total) by (method, status)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Upload Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Latency",
     "type": "timeseries",
     "description": "Shows the 95th percentile latency for each gRPC method.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 419 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(upload_service_grpc_request_duration_seconds_bucket[1m])) by (le, method))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests by Method",
     "type": "timeseries",
     "description": "Displays the request rate for each gRPC method.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 419 },
     "targets": [
      {
       "expr": "sum(rate(upload_service_grpc_requests_total[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error Rate",
     "type": "piechart",
     "description": "Visualizes the proportion of failed requests.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 449 },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "expr": "sum by(status) (rate(upload_service_grpc_requests_total{status!=\"OK\"}[24h]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Requests",
     "type": "timeseries",
     "description": "Displays the total requests grouped by method and status.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 449 },
     "targets": [
      {
       "expr": "sum(upload_service_grpc_requests_total) by (method, status)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Encode Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Message Processing Duration",
   "type": "timeseries",
   "description": "Shows the 95th percentile latency for each RabbitMQ message.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(encode_service_message_processing_duration_seconds[1m])) by (message_type))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages by Message Type",
   "type": "timeseries",
   "description": "Displays the message rate for each message_type.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(encode_service_messages_total[1m])) by (message_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "piechart",
   "description": "Visualizes the proportion of failed requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum by(reason) (rate(encode_service_message_processing_errors_total{}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Messages",
   "type": "timeseries",
   "description": "Total number of messages received from RabbitMQ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(encode_service_messages_total) by (message_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Video Catalog Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "description": "Shows the 95th percentile latency for each gRPC method.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(video_catalog_service_grpc_request_duration_seconds_bucket[1m])) by (le, method))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by Method",
   "type": "timeseries",
   "description": "Displays the request rate for each gRPC method.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(video_catalog_service_grpc_requests_total[1m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GRPC Error Rate",
   "type": "piechart",
   "description": "Visualizes the proportion of failed requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum by(status) (rate(video_catalog_service_grpc_requests_total{status!=\"OK\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "description": "Displays the total requests grouped by method and status.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum(video_catalog_service_grpc_requests_total) by (method, status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages by Message Type",
   "type": "timeseries",
   "description": "Displays the message rate for each message_type.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(rate(video_catalog_service_messages_total[1m])) by (message_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Messages",
   "type": "timeseries",
   "description": "Total number of messages received from RabbitMQ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "sum(video_catalog_service_messages_total) by (message_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RabbitMQ Messages Error Rate",
   "type": "piechart",
   "description": "Visualizes the proportion of failed messages.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum by(reason) (rate(video_catalog_service_message_processing_errors_total{}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Message Processing Duration",
   "type": "timeseries",
   "description": "Shows the 95th percentile latency for each RabbitMQ message.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(video_catalog_service_message_processing_duration_seconds[1m])) by (message_type))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}