apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
  namespace: microservices
  labels:
    app: authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
        - name: authentication-service
          image: kind-registry:5000/authentication-service:1.0
          envFrom:
            - configMapRef:
                name: authentication-service
            - secretRef:
                name: authentication-service
          ports:
            - containerPort: 5001
              protocol: TCP
            - containerPort: 5011
              protocol: TCP
          livenessProbe:
            grpc:
              port: 5001
            initialDelaySeconds: 20
            periodSeconds: 45
          readinessProbe:
            grpc:
              port: 5001
            initialDelaySeconds: 20
            periodSeconds: 45
          resources:
            requests:
              memory: "150Mi"
              cpu: "200m"
            limits:
              memory: "150Mi"
              cpu: "200m"
