apiVersion: v1
kind: Secret
metadata:
  name: authentication-service
  namespace: microservices
data:
  JWT_SECRET: T0dReFlqZ3hOakk0WkRWbE16RXdZell5TWpnd09ERXhNV00yWmpNNFkyUT0= #base64 for "OGQxYjgxNjI4ZDVlMzEwYzYyMjgwODExMWM2ZjM4Y2Q="
