apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service
  namespace: microservices
data:
  NODE_ENV: "production"

  GRPC_HOST: "0.0.0.0"
  GRPC_PORT: "5000"

  DB_HOST: "user-db.datastores.svc.cluster.local"
  DB_DATABASE: "microservices_user_service"
  DB_PORT: "5432"
  DB_LOGGING: "0"

  PROMETHEUS_METRICS_HOST: "0.0.0.0"
  PROMETHEUS_METRICS_PORT: "5010"

  # GRPC_VERBOSITY="DEBUG"
  # GRPC_TRACE="all"
