apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: microservices
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - name: grpc
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: http
      protocol: TCP
      port: 5010
      targetPort: 5010
