apiVersion: v1
kind: ConfigMap
metadata:
  name: video-catalog-service
  namespace: microservices
data:
  GRPC_HOST: "0.0.0.0"
  GRPC_PORT: "5003"
  GRPC_USER_SERVICE_URL: "user-service.microservices.svc.cluster.local:5000"
  GRPC_CLIENT_TIMEOUT_SECONDS: "5"

  PROMETHEUS_METRICS_HOST: "0.0.0.0"
  PROMETHEUS_METRICS_PORT: "5013"

  DB_HOST: "video-catalog-db.datastores.svc.cluster.local"
  DB_PORT: "5432"
  DB_DATABASE: "microservices_video_catalog_service"
  DB_SSLMODE: "disable"
  DB_TIMEZONE: "UTC"

  AMQP_HOST: "rabbitmq.datastores.svc.cluster.local"
  AMQP_PORT: "5672"

  AWS_REGION: "us-east-1"
  AWS_S3_PRESIGNED_URL_EXPIRY: "15"
