apiVersion: v1
kind: Service
metadata:
  name: video-catalog-service
  namespace: microservices
spec:
  type: ClusterIP
  selector:
    app: video-catalog-service
  ports:
    - name: grpc
      protocol: TCP
      port: 5003
      targetPort: 5003
    - name: http
      protocol: TCP
      port: 5013
      targetPort: 5013
