apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus-ds  # Custom UID
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: GET

  - name: Loki
    type: loki
    uid: loki-ds  # Custom UID
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
