apiVersion: v1
kind: Secret
metadata:
  name: upload-service
  namespace: microservices
data:
  AWS_ACCESS_KEY: key
  AWS_SECRET_KEY: secret
  AWS_S3_BUCKET: bucket

  AMQP_USERNAME: ZGVmYXVsdA== #base64 for "default"
  AMQP_PASSWORD: ZGVmYXVsdA== #base64 for "default"
