global:
  scrape_interval: 8s

scrape_configs:
  - job_name: api-gateway
    static_configs:
      - targets:
          - "api-gateway:4000"
    metric_relabel_configs:
      - source_labels: [__name__]
        target_label: __name__
        regex: "(.*)"
        action: replace
        replacement: api_gateway_${1}

  - job_name: user-service
    static_configs:
      - targets:
          - "user-service:5010"
    metric_relabel_configs:
      - source_labels: [__name__]
        target_label: __name__
        regex: "(.*)"
        action: replace
        replacement: user_service_${1}

  - job_name: authentication-service
    static_configs:
      - targets:
          - "authentication-service:5011"
    metric_relabel_configs:
      - source_labels: [__name__]
        target_label: __name__
        regex: "(.*)"
        action: replace
        replacement: authentication_service_${1}

  - job_name: upload-service
    static_configs:
      - targets:
          - "upload-service:5012"
    metric_relabel_configs:
      - source_labels: [__name__]
        target_label: __name__
        regex: "(.*)"
        action: replace
        replacement: upload_service_${1}

  - job_name: video-catalog-service
    static_configs:
      - targets:
          - "video-catalog-service:5013"
    metric_relabel_configs:
      - source_labels: [__name__]
        target_label: __name__
        regex: "(.*)"
        action: replace
        replacement: video_catalog_service_${1}

  - job_name: encode-service
    static_configs:
      - targets:
          - "encode-service:5014"
    metric_relabel_configs:
      - source_labels: [__name__]
        target_label: __name__
        regex: "(.*)"
        action: replace
        replacement: encode_service_${1}

  - job_name: redis
    static_configs:
      - targets:
          - "redis-exporter:9121"

  - job_name: rabbitmq
    static_configs:
      - targets:
          - "rabbitmq-exporter:9419"

  - job_name: postgresql
    static_configs:
      - targets:
          - "user-db-exporter:9187"
          - "video-catalog-db-exporter:9187"
